"""Builds src/splash_data.h: the Capybara Editor's 10 loading frames (delta + LZ4) and the gold title."""
import sys
from PIL import Image
import lz4.block as B
sys.path.insert(0, sys.path[0])
from title import text

SRC = sys.argv[1]            # folder with door-v7-0..9.png
TITLE = 'MXL Capybara Calculator'
fr = [Image.open(f'{SRC}/door-v7-{i}.png').convert('RGB').tobytes() for i in range(10)]
d = bytearray(fr[0])
for i in range(1, 10):
    d += bytes((a - b) & 255 for a, b in zip(fr[i], fr[i - 1]))
comp = B.compress(bytes(d), mode='high_compression', compression=12, store_size=False)
assert B.decompress(comp, uncompressed_size=len(d)) == bytes(d)
tw, th, tpx = text(TITLE)


def arr(name, data):
    rows = [', '.join(str(b) for b in data[i:i + 40]) for i in range(0, len(data), 40)]
    return f'static const unsigned char {name}[{len(data)}] = {{\n' + ',\n'.join(rows) + '\n};\n'


with open(sys.argv[2], 'w') as f:
    f.write('/* Generated by tools/build_data.py: loading frames of the MXL Capybara Editor (D2 door with the capybara,\n'
            ' * 10 x 256x256 RGB, frame deltas, LZ4 block) and the title in fontexocet10 (solid gold, outlined). */\n')
    f.write(f'#define SPL_SIZE 256\n#define SPL_FRAMES 10\n#define SPL_RAW {len(d)}\n')
    f.write(f'#define SPL_TITLE_W {tw}\n#define SPL_TITLE_H {th}\n')
    f.write(arr('SPL_LZ4', comp))
    f.write(arr('SPL_TITLE', tpx))
print('lz4', len(comp), 'title', tw, th)
